apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: go-crud-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}
