name: Build and Push Docker Image

on:
  push:
    # branches:
    #   - main
    tags:
      - v3.3.3 

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image and Push
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gocrudapp:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/gocrudapp:$IMAGE_TAG